apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-custom-default-branch-fvpu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-custom-default-branch-fvpu
    app.kubernetes.io/part-of: build-suite-test-application-xohi
  name: test-custom-default-branch-fvpu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-custom-default-branch-fvpu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-custom-default-branch-fvpu
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-myxf-tenant/build-suite-test-application-xohi/test-custom-default-branch-fvpu@sha256:3ffb06d55e2d1075a374f524a42a8dd830e13eac0a048cc4cc74ce0575a9532b
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
