apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-custom-default-branch-fvpu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-custom-default-branch-fvpu
    app.kubernetes.io/part-of: build-suite-test-application-xohi
  name: test-custom-default-brancalul
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-custom-default-branch-fvpu
    weight: 100
status: {}
